#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/cryptecs/corporate-information.
#
# SPDX-License-Identifier: CC-BY-4.0
#
repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.7
    hooks:
      - id: mdformat
        args:
          - --wrap
          - "80"
        additional_dependencies:
          - mdformat-gfm
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint